name: my_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2

  # The following adds the Cutino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  stylish_bottom_bar: ^1.1.1
  font_awesome_flutter:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  awesome_snackbar_content: ^0.1.7
  flutter_gemini: ^3.0.0
  easy_localization: ^3.0.7 # Switched to easy_localization
  gif: ^2.3.0
  google_sign_in: ^6.2.1
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/ # For easy_localization
    - assets/green_tree/
    - assets/cherry_blossom/
    - assets/palm_tree/
    - assets/autumn_tree/

  fonts:
    - family: NTBrickSans
      fonts:
        - asset: fonts/NTBrickSans.ttf
