// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26-nKc48nAYquwLC9v-op52Im1tIf_a4',
    appId: '1:1052124070100:android:345e8e2deda65fb11d7b41',
    messagingSenderId: '1052124070100',
    projectId: 'farmerapp-45e2e',
    storageBucket: 'farmerapp-45e2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfd1mr0oin0wKGqbYI2WuiqAOuZeR1g_c',
    appId: '1:1052124070100:ios:0ad8be6833c614171d7b41',
    messagingSenderId: '1052124070100',
    projectId: 'farmerapp-45e2e',
    storageBucket: 'farmerapp-45e2e.firebasestorage.app',
    androidClientId: '1052124070100-5j9pfi23dmallh303aapugl1c67o0eo2.apps.googleusercontent.com',
    iosClientId: '1052124070100-bh8i68j1og2olf34a0l1p1jhq5h2f87r.apps.googleusercontent.com',
    iosBundleId: 'com.jeevankhet.jeevankhet',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJASPIAoiu-jP4RNGhpGwRgqtwf1khO_g',
    appId: '1:1052124070100:web:092ddfa95b49c2551d7b41',
    messagingSenderId: '1052124070100',
    projectId: 'farmerapp-45e2e',
    authDomain: 'farmerapp-45e2e.firebaseapp.com',
    storageBucket: 'farmerapp-45e2e.firebasestorage.app',
    measurementId: 'G-FVEHZ1N1DV',
  );

}